### ISSUE TITLE
camera parameter missing

### ISSUE THREAD

**Issue by ssh1999** [cdiazruiz/ithaca365-devkit#2]
Hi, thanks for providing this great work!
I'm trying to use this dataset currently. But i found that the extrinstic and intrinstic matrix of camera 1 and camera 3 are missing in the sensor.json and calibrated_sensor.json. Can you tell me how to get the camera paramters of cam1 and cam3? 
Thank you.

![image](https://user-images.githubusercontent.com/116867865/230123340-ac37114d-4f0e-4e77-9e71-0b28e94267fc.png)

**Comment by cdiazruiz** [comment]
Currently the sdk only has the parameters for cam0 and cam2. I'll add the other parameters in the next couple of days.

**Comment by ssh1999** [comment]
I see. Thanks for your quick reply!
Besides, I want to ask, is the coordinate system the same as the OpenCV coordinate system (i.e., `(x,-y,-z) (right, down, forward)` )?

**Comment by cdiazruiz** [comment]
It's the same as nuscenes. But yes, z is forward, and x is right.
