### ISSUE TITLE
Export to kitti

### ISSUE THREAD

**Issue by psriram2** [cdiazruiz/ithaca365-devkit#3]
Hi,

I cannot download the full dataset due to memory constraints. I'm trying to do 3d object detection task and I downloaded just the 40 traversals. I tried to use export_kitti.py to change the traversals and annotations to kitti format but getting bunch of errors. Could you please provide instructions on how to do this?

**Comment by cdiazruiz** [comment]
Hello,
I have not verified if export_kitti.py works with how we set up our tables.

**Comment by psriram2** [comment]
Ok, thank you for your reply
