### ISSUE TITLE
lidar to camera

### ISSUE THREAD

**Issue by ZehongW07** [cdiazruiz/ithaca365-devkit#7]
Hi, thanks for your contribution!
I'm using your 40 traversals subsampled dataset to run the code in your tutorial. 
`dataset.render_pointcloud_in_image(my_sample['token'], pointsensor_channel='LIDAR_TOP', camera_channel='cam0')`
The run comes out like this, and it feels like the lidar point cloud and the image don't match up.
<img width="523" alt="lid2img" src="https://github.com/cdiazruiz/ithaca365-devkit/assets/149024670/58da8753-fc1e-484b-9379-603a1c12ea25">

**Comment by cdiazruiz** [comment]
Sorry about that. We will look into it

**Comment by wangjiyuan9** [comment]
fixed？

**Comment by cdiazruiz** [comment]
I expect to have fixed by today. Currently uploading corrected lidar pointclouds

**Comment by cdiazruiz** [comment]
I have reuploaded the lidars:  ("01-17-2022b" "01-17-2022c" "01-20-2022" "01-23-2022" "02-25-2022" "03-03-2022b" "11-23-2021" "12-01-2021").
