### ISSUE TITLE
Some issue about point cloud files.

### ISSUE THREAD

**Issue by Liquid111** [cdiazruiz/ithaca365-devkit#8]
Hi, thanks for your contribution!
I'm using your dataset for 3D object detection research. 
But in the process of experiment, I found that the point cloud file may not be correctly organized, causing wrong coordinate of the point clouds. By analysing the data, I can determine that the issue comes with the point cloud files. 
The point cloud files in the subsampled data may be all incorrect and the point cloud files in several scenes of the full dataset can be not correct either.
I believe that the dataset is a very useful work for the autonomous driving research, and hope you can correct the issues for better usage.

**Comment by Liquid111** [comment]
By the way, the possible scenes with errors in the full data may contain"01-17-2022b, 01-17-2022c, 01-20-2022, 01-23-2022, 02-25-2022, 03-03-2022b, 11-23-2021, 12-01-2021"

**Comment by cdiazruiz** [comment]
Hello,

thanks for pointing that out. Currently looking into this issue

**Comment by malicd** [comment]
Hi, are there any updates on this? I have also identified a number of frames which have questionable point clouds, for instance `12-03-2021/decoded_lidar/1638559757014774016.bin`:
![ScreenCapture_2024-02-21-18-03-54](https://github.com/cdiazruiz/ithaca365-devkit/assets/33249303/89f1147a-274f-4f01-bb0a-e3627d2156f4)
![1638559757028497](https://github.com/cdiazruiz/ithaca365-devkit/assets/33249303/73ea571c-13ce-4ff5-bc26-ad1dd2d381e0)

**Comment by cdiazruiz** [comment]
Yes, we are working on re-uploading the data onto the server within the next week. Should also note that there are dates that inherently have less points in the point cloud if it was raining, or snowing. We did our best to clean the sensor between drives, but this sensor outputs less points/returns if droplets, snow or dust got on it.

**Comment by malicd** [comment]
Thanks for the information and looking forward for the update!

> Should also note that there are dates that inherently have less points in the point cloud if it was raining, or snowing. We did our best to clean the sensor between drives, but this sensor outputs less points/returns if droplets, snow or dust got on it.

This is completely understandable and one of the reasons why the community finds your adverse weather dataset valuable. However, the example frame from above is from a sunny drive (as shown in the image below).

**Comment by cdiazruiz** [comment]
I expect to have uploaded the fixed "01-17-2022b, 01-17-2022c, 01-20-2022, 01-23-2022, 02-25-2022, 03-03-2022b, 11-23-2021, 12-01-2021" by today.

**Comment by cdiazruiz** [comment]
I have reuploaded the lidars:  ("01-17-2022b" "01-17-2022c" "01-20-2022" "01-23-2022" "02-25-2022" "03-03-2022b" "11-23-2021" "12-01-2021").

**Comment by Liquid111** [comment]
> I have reuploaded the lidars: ("01-17-2022b" "01-17-2022c" "01-20-2022" "01-23-2022" "02-25-2022" "03-03-2022b" "11-23-2021" "12-01-2021").

That's great! Thanks for your contribution to the autonomous driving community!
